const express = require('express');
const multer = require('multer');
const nodemailer = require('nodemailer');

const router = express.Router();

// Configure multer for file uploads
const storage = multer.memoryStorage();
const upload = multer({
    storage: storage,
    limits: { fileSize: 10 * 1024 * 1024 } // 10MB limit
});

// Create email transporter (only if SMTP is configured)
function createTransporter() {
    // Check if SMTP is properly configured
    if (!process.env.SMTP_HOST || !process.env.SMTP_USER || !process.env.SMTP_PASS) {
        return null;
    }

    return nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: parseInt(process.env.SMTP_PORT || '587'),
        secure: process.env.SMTP_SECURE === 'true',
        auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS
        }
    });
}

// Send email with data
async function sendEmailWithData(emailData) {
    try {
        // Check if SMTP is properly configured
        if (!process.env.SMTP_HOST || !process.env.SMTP_USER || !process.env.SMTP_PASS) {
            console.log('📧 Email not configured - skipping email send');
            throw new Error('Email service not configured. Please set up SMTP settings in your environment variables.');
        }

        if (!process.env.EMAIL_TO) {
            console.log('📧 EMAIL_TO not configured - skipping email send');
            throw new Error('EMAIL_TO not configured in environment variables');
        }

        const transporter = createTransporter();
        if (!transporter) {
            throw new Error('Email transporter could not be created');
        }

        const { pricing, salesText, image, productName } = emailData;

        const mailOptions = {
            from: process.env.SMTP_USER,
            to: process.env.EMAIL_TO,
            subject: `Product Analysis: ${productName}`,
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
                    <h2 style="color: #333; border-bottom: 2px solid #667eea; padding-bottom: 10px;">
                        📸 Product Analysis Results
                    </h2>
                    
                    <div style="background: #e8f5e8; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
                        <h3 style="margin-top: 0; color: #2e7d32;">💰 Pricing Information:</h3>
                        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px;">
                            <div style="background: white; padding: 10px; border-radius: 6px; text-align: center;">
                                <strong style="color: #6c757d; font-size: 14px;">New Price</strong><br>
                                <span style="font-size: 18px; font-weight: bold; color: #28a745;">${pricing.newPrice}</span>
                            </div>
                            <div style="background: white; padding: 10px; border-radius: 6px; text-align: center;">
                                <strong style="color: #6c757d; font-size: 14px;">Used Price</strong><br>
                                <span style="font-size: 18px; font-weight: bold; color: #28a745;">${pricing.usedPrice}</span>
                            </div>
                        </div>
                        <div style="background: white; padding: 10px; border-radius: 6px;">
                            <strong style="color: #495057;">Pricing Reasoning:</strong><br>
                            <span style="color: #6c757d;">${pricing.reasoning}</span>
                        </div>
                    </div>
                    
                    <div style="background: #fff3e0; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
                        <h3 style="margin-top: 0; color: #f57c00;">📝 Sales Text:</h3>
                        <div style="background: white; padding: 15px; border-radius: 6px; border: 1px solid #dee2e6;">
                            <pre style="margin: 0; font-family: inherit; white-space: pre-wrap; color: #495057;">${salesText}</pre>
                        </div>
                    </div>
                    
                    ${image ? `
                    <div style="text-align: center; margin-top: 20px;">
                        <p style="color: #6c757d; font-style: italic;">📎 Product image attached to this email</p>
                    </div>
                    ` : ''}
                    
                    <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6; text-align: center; color: #6c757d; font-size: 12px;">
                        <p>Generated by Onisad Sales Assistant</p>
                    </div>
                </div>
            `,
            attachments: image ? [{
                filename: 'product-image.jpg',
                content: image,
                contentType: 'image/jpeg'
            }] : []
        };

        const result = await transporter.sendMail(mailOptions);
        console.log(`✅ Email sent successfully to ${process.env.EMAIL_TO}:`, result.messageId);
        return { success: true, messageId: result.messageId };

    } catch (error) {
        console.error('📧 Email error:', error.message);
        throw error; // Re-throw to handle in the endpoint
    }
}

// Send email endpoint (mounted at /email, so route is /email/send-email)
router.post('/send-email', upload.single('image'), async (req, res) => {
    try {
        const { pricing, salesText, productName } = req.body;

        if (!pricing || !salesText) {
            return res.status(400).json({ error: 'Pricing and sales text are required' });
        }

        const emailData = {
            pricing: JSON.parse(pricing),
            salesText,
            image: req.file ? req.file.buffer : null,
            productName: productName || 'Unknown Product'
        };

        const result = await sendEmailWithData(emailData);

        res.json({
            success: true,
            message: 'Email sent successfully',
            messageId: result.messageId
        });

    } catch (error) {
        console.error('Email sending error:', error);
        res.status(500).json({
            error: 'Email sending failed',
            message: error.message
        });
    }
});

module.exports = {
    router,
    sendEmailWithData
};
